package com.example.barbershop.QuestionType

class SurveyResultDataBaseModule (
         val id  : String,
         var I1  : String,
         var I2  : String ,
         var I3  : String ,
         var I4  : String ,
         var I5  : String ,
         var I6  : String ,
         var I7  : String  ,
         var Q1  : String  ,
         var Q1A : String,
         var Q2  : String ,
         var Q3  : String ,
         var Q3A : String ,
         var Q4  : String  ,
         var Q5  : String ,
         var Q6  : String ,
         var Q7  : String ,
         var Q7A : String ,
         var Q7B : String ,
         var Q8  : String  ,
         var Q8A : String ,
         var Q9  : String ,
         var Q9A : String,
         var Q10 : String ,
         var Q11 : String,
         var Q12 : String ,
         var Q13 : String ,
         var Q13A: String,
         var Q14 : String ,
         var Q15 : String,
         var Q15A: String ,
         var Q16 : String,
         var Q16A: String,
         var Q17 : String ,
         var Q17A: String,
         var Q18 : String ,
         var Q19 : String ,
         var Q19A: String,
         var Q20 : String ,
         var Q20A: String ,
         var Q21 : String ,
         var Q21A: String,
         var Q22 : String ,
         var Q23 : String,
         var Q24 : String,
         var Q25 : String ,
         var Q26 : String,
         var Q26A: String ,
         var Q27 : String ,
         var Q27A: String,
         var Q28 : String,
         var Q28A: String ,
         var Q29 : String ,
         var Q30 : String
)

